### PR TITLE
Barnes and Laika ice caps

### PR DESCRIPTION
**Pull request by mankoff**
See issues #39

### CODE REVIEW

**Comment by mankoff** [comment]
@mjacqu - Please review the new README.org and data.csv files for Laika and Barnes. Also you can see all the metadata for each borehole here: https://docs.google.com/spreadsheets/d/1QNqnjO7Gocl29Y7X693rCRRZI4dTSq0i58YghWeHy2Q/edit?usp=sharing

**Comment by mankoff** [comment]
Needs actual (not approximate) ice thickness.

**Comment by mjacqu** [comment]
With regard to ice thicknesses:
Barnes: 
14.3: 220m (from Classen 1977)
19.5: 192m (from Classen 1977)
24.55: 115m (from Classen 1977)
T0975: 50m (from Hooke 1980)
T091: 94m (from Hooke 1980)
T081: 156m (from Hooke 1980)
T061: 220m (from Hooke 1980)
T020: 270m (from Hooke 1980)
B4: 110m (from Hooke 1980)
D4 (C4 in Gilbert et al., 2016): 80m (from Hooke 1980)

Laika (estimated from figures 8 and 12 in Blatter 1988):
X1: 72m
X2: 90m
X3: 108m
X4: 99m
X5: 50m

Metadata:
Data for Barnes Ice Cap Barnes_B4_1974, Barnes_D4_1974, Barnes_T0975_1976, Barnes_T091_1977, Barnes_T081_1978, Barnes_T061_1977, Barnes_T020_1979 was digitized from Gilbert et al., 2016 (10.1002/2016JF003839), the ice thickness is taken from Hooke et al., 1980. 
The locations of these boreholes was also digitized from Gilbert et al., 2016.

All other locations (Barnes from Classen and Laika) were estimated by myself comparing the published maps and modern aerial images.

**Comment by mankoff** [comment]
I disagree with

> 
> T0975: 50m (from Hooke 1980)
> T091: 94m (from Hooke 1980)
> T081: 156m (from Hooke 1980)
> T061: 220m (from Hooke 1980)
> T020: 270m (from Hooke 1980)
> B4: 110m (from Hooke 1980)
> D4 (C4 in Gilbert et al., 2016): 80m (from Hooke 1980)

Using the following Fig. 3 from Hooke (1980):

image

It appears that:
+ Top of 975 is ~115 m above bed
+ Top of 091 is ~140
+ Top of 081 is ~185
+ Top of 061 is ~240
+ Top of 020 is ~370

Table 1 of Hooke (1980) lists these as:
+ 0975: 115
+ 091: 140
+ 081: 173
+ 061: 239
+ 020: 369

I am using these published table values for now.

**Pull request merged**
